spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/rustdesk.db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 3000ms

############## Sa-Token Configuration ##############
sa-token:
  # Token name (also cookie name)
  token-name: satoken
  # Token timeout (in seconds, -1 means never expire)
  timeout: 604800
  # Active timeout (in seconds, -1 means never expire)
  active-timeout: -1
  # Whether to allow concurrent login from same account
  is-concurrent: true
  # Whether to share token across multiple devices
  is-share: false
  # Token style (random-32, random-64, random-128, uuid, simple-uuid)
  token-style: uuid
  # Whether to output logs
  is-log: false
  # Whether to read token from cookie
  is-read-cookie: false
  # Whether to read token from header
  is-read-header: true
  # Token prefix (e.g. "Bearer ")
  token-prefix: "Bearer"

rustdesk:
  app:
    show-swagger: true

logging:
  level:
    root: INFO
    com.rustdesk.api: DEBUG
