spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:rustdesk}?useUnicode=true&characterEncoding=utf8&useSSL=${MYSQL_SSL:false}&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms

rustdesk:
  app:
    show-swagger: false

logging:
  level:
    root: INFO
    com.rustdesk.api: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
